DOWNLOAD_FOLDER = "FULL_PATH_TO_DOWNLOAD_FOLDER"
SPOTIFY_PLAYLIST_URL = "PAST_YOUR_PLAYLIST_HERE"
DOWNLOAD_TIMEOUT = 300
ELEMENT_WAIT_TIMEOUT = 30
CLIENT_ID='YOUR_CLIENT_ID_HERE',
CLIENT_SECRET='YOUR_CLIENT_SECRET_HERE'